// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: './apps/auth/prisma/schema.prisma',
  migrations: {
    path: './apps/auth/prisma/migrations',
  },
  datasource: {
    url: process.env.DATABASE_URL as string,
  },
});
